name: Example
version: 1.2.4
main: com.stageroad0820.Example.Main
description: Tutorial Plugin!

commands:
  blog:
    description: Blog Tutorial - Player Commands!
  cs:
    description: Blog Tutorial - Console Commands!